import json
import re

from langchain_ollama import ChatOllama

from config import SemanticFilter, SemanticQuery
from cube_converter import semantic_to_cube
from prompts import build_system_prompt
from semantic_schema import (
    APPROVED_DIMENSIONS,
    APPROVED_MEASURES,
)
from snowflake_executor import execute_query
from sql_builder import build_sql


MODEL_NAME = "llama3.2:3b"


VALID_REGIONS = [
    "Africa",
    "Canada",
    "Caribbean",
    "Central",
    "Central Asia",
    "EMEA",
    "East",
    "North",
    "North Asia",
    "Oceania",
    "South",
    "Southeast Asia",
    "West",
]


MEASURE_ALIASES = {
    "total_sales": "total_sales",
    "totalsales": "total_sales",
    "sales": "total_sales",
    "revenue": "total_sales",
    "totalrevenue": "total_sales",
    "total_revenue": "total_sales",

    "total_profit": "total_profit",
    "totalprofit": "total_profit",
    "profit": "total_profit",
    "net_profit": "total_profit",
    "netprofit": "total_profit",

    "total_quantity": "total_quantity",
    "totalquantity": "total_quantity",
    "quantity": "total_quantity",
    "units_sold": "total_quantity",
    "unitssold": "total_quantity",

    "average_sales": "average_sales",
    "averagesales": "average_sales",
    "avg_sales": "average_sales",
    "avgsales": "average_sales",
    "average_revenue": "average_sales",

    "order_count": "order_count",
    "ordercount": "order_count",
    "orders": "order_count",

    "customer_count": "customer_count",
    "customercount": "customer_count",
    "customers": "customer_count",

    "total_shipping_cost": "total_shipping_cost",
    "totalshippingcost": "total_shipping_cost",
    "shipping_cost": "total_shipping_cost",
    "shippingcost": "total_shipping_cost",
    "freight_cost": "total_shipping_cost",
    "freightcost": "total_shipping_cost",
    "shipment_cost": "total_shipping_cost",

    "average_discount": "average_discount",
    "averagediscount": "average_discount",
    "discount": "average_discount",

    "estimated_cost": "estimated_cost",
    "estimatedcost": "estimated_cost",
    "cost": "estimated_cost",

    "profit_margin_percentage": "profit_margin_percentage",
    "profitmarginpercentage": "profit_margin_percentage",
    "profit_margin": "profit_margin_percentage",
    "profitmargin": "profit_margin_percentage",
}


DIMENSION_ALIASES = {
    "region": "region",
    "country": "country",
    "market": "market",
    "category": "category",
    "sub_category": "sub_category",
    "subcategory": "sub_category",
    "sub category": "sub_category",
    "segment": "segment",
    "ship_mode": "ship_mode",
    "shipmode": "ship_mode",
    "ship mode": "ship_mode",
    "state": "state",
    "city": "city",
    "customer_id": "customer_id",
    "customerid": "customer_id",
    "customer_name": "customer_name",
    "customername": "customer_name",
    "product_id": "product_id",
    "productid": "product_id",
    "product_name": "product_name",
    "productname": "product_name",
    "order_date": "order_date",
    "orderdate": "order_date",
    "order date": "order_date",
}


def normalize_name(value: str) -> str:
    """
    Convert names such as average_Sales, Ship Mode and
    sub-category into a consistent lowercase format.
    """

    cleaned = value.strip().lower()
    cleaned = cleaned.replace("'", "").replace('"', "")
    cleaned = cleaned.replace("=", "_").replace("-", "_")
    cleaned = cleaned.replace("/", "_").replace(".", "_")
    cleaned = re.sub(r"\s+", " ", cleaned)
    return cleaned.strip("_")


def parse_member_value(value: str) -> tuple[str, str | None]:
    """Split a member/value string such as region='Europe' or region:Europe."""

    text = value.strip()
    if not text:
        return "", None

    for separator in (":", "="):
        if separator in text:
            member, raw_value = text.split(separator, 1)
            member = member.strip().strip("'\"` ")
            raw_value = raw_value.strip().strip("'\"` ")
            if member:
                return member, raw_value or None

    return text, None


def normalize_measure(measure: str) -> str:
    """
    Normalize measure names generated by the LLM.
    """

    member, _ = parse_member_value(measure)
    normalized = normalize_name(member)
    compact = normalized.replace("_", "").replace(" ", "")

    if normalized in MEASURE_ALIASES:
        return MEASURE_ALIASES[normalized]

    if compact in MEASURE_ALIASES:
        return MEASURE_ALIASES[compact]

    return normalized.replace(" ", "_")


def normalize_dimension(dimension: str) -> str:
    """
    Normalize dimension names generated by the LLM.
    """

    member, _ = parse_member_value(dimension)
    normalized = normalize_name(member)

    if normalized in DIMENSION_ALIASES:
        return DIMENSION_ALIASES[normalized]

    compact = normalized.replace("_", "").replace(" ", "")

    if compact in DIMENSION_ALIASES:
        return DIMENSION_ALIASES[compact]

    return normalized.replace(" ", "_")


def is_rank_indicator(value: str) -> bool:
    """Return True for phrases such as 'top 5', 'bottom 3', or 'top_5'."""

    normalized = normalize_name(value)
    return bool(
        re.fullmatch(r"(?:top|bottom)(?:[_-]?\d+)", normalized)
    )


def validate_semantic_query(
    query: SemanticQuery,
) -> None:
    """
    Validate measures, dimensions and filter members.
    """

    if query.measure not in APPROVED_MEASURES:
        raise ValueError(
            f"Unsupported measure: {query.measure}"
        )

    for dimension in query.dimensions:
        if dimension not in APPROVED_DIMENSIONS:
            raise ValueError(
                f"Unsupported dimension: {dimension}"
            )

    if (
        query.time_dimension is not None
        and query.time_dimension
        not in APPROVED_DIMENSIONS
    ):
        raise ValueError(
            "Unsupported time dimension: "
            f"{query.time_dimension}"
        )

    for semantic_filter in query.filters:
        if (
            semantic_filter.member
            not in APPROVED_DIMENSIONS
        ):
            raise ValueError(
                "Unsupported filter member: "
                f"{semantic_filter.member}"
            )


def create_query_planner():
    """
    Create the LangChain and Ollama query planner.
    """

    model = ChatOllama(
        model=MODEL_NAME,
        temperature=0,
    )

    return model.with_structured_output(
        SemanticQuery
    )


def normalize_semantic_query(
    query: SemanticQuery,
) -> SemanticQuery:
    """
    Normalize the complete LLM-generated query before
    applying deterministic rules.
    """

    query.measure = normalize_measure(
        query.measure
    )

    normalized_dimensions = []

    for dimension in query.dimensions:
        dimension = dimension.strip()
        member, value = parse_member_value(dimension)

        if value is not None:
            normalized_member = normalize_dimension(member)
            normalized_dimensions.append(
                f"{normalized_member}:{value.strip()}"
            )
        else:
            normalized_dimensions.append(
                normalize_dimension(dimension)
            )

    query.dimensions = normalized_dimensions

    for semantic_filter in query.filters:
        semantic_filter.member = normalize_dimension(
            semantic_filter.member
        )

        semantic_filter.operator = (
            semantic_filter.operator
            .strip()
            .lower()
        )

    if query.time_dimension is not None:
        query.time_dimension = normalize_dimension(
            query.time_dimension
        )

    if query.order is not None:
        query.order = query.order.strip().lower()

    return query


def apply_query_rules(
    question: str,
    query: SemanticQuery,
) -> SemanticQuery:
    """
    Correct common LLM output problems.
    """

    normalized_question = (
        question.lower().strip()
    )

    query = normalize_semantic_query(query)
    query.dimensions = [
        dimension
        for dimension in query.dimensions
        if not is_rank_indicator(dimension)
    ]
    query.filters = [
        semantic_filter
        for semantic_filter in query.filters
        if not is_rank_indicator(semantic_filter.member)
    ]

    simple_total_sales_questions = {
        "total sales",
        "show total sales",
        "what are the total sales",
        "what is total sales",
        "what is the total sales",
        "overall sales",
        "show overall sales",
        "show me total sales",
    }

    if (
        normalized_question
        in simple_total_sales_questions
    ):
        query.measure = "total_sales"
        query.dimensions = []
        query.filters = []
        query.time_dimension = None
        query.time_granularity = None
        query.order = None
        query.limit = 100

        return query

    # Convert dimensions such as region:West
    # into proper filters.
    clean_dimensions = []

    for dimension in query.dimensions:
        member, value = parse_member_value(dimension)

        if value is not None:
            member = normalize_dimension(member)
            value = value.strip()

            if member in APPROVED_DIMENSIONS:
                filter_exists = any(
                    semantic_filter.member == member
                    for semantic_filter in query.filters
                )

                if not filter_exists:
                    query.filters.append(
                        SemanticFilter(
                            member=member,
                            operator="equals",
                            values=[value],
                        )
                    )
            else:
                clean_dimensions.append(dimension)
            continue

        normalized_dimension = normalize_dimension(dimension)
        clean_dimensions.append(normalized_dimension)

    query.dimensions = clean_dimensions

    # Detect region value in the user question.
    matched_region = None

    sorted_regions = sorted(
        VALID_REGIONS,
        key=len,
        reverse=True,
    )

    for region in sorted_regions:
        region_pattern = (
            r"\b"
            + re.escape(region.lower())
            + r"\b"
        )

        if re.search(
            region_pattern,
            normalized_question,
        ):
            matched_region = region
            break

    if matched_region is not None:
        # For "sales for Africa", region is a filter,
        # not a grouping dimension.
        query.dimensions = [
            dimension
            for dimension in query.dimensions
            if dimension not in {
                "region",
                "market",
            }
            and dimension.lower()
            != matched_region.lower()
        ]

        # Remove invalid or duplicate region filters.
        query.filters = [
            semantic_filter
            for semantic_filter in query.filters
            if semantic_filter.member != "region"
            and semantic_filter.member.lower()
            != matched_region.lower()
        ]

        query.filters.append(
            SemanticFilter(
                member="region",
                operator="equals",
                values=[matched_region],
            )
        )

    # Detect queries such as:
    # top 5 regions by sales
    # top 10 categories by profit
    top_match = re.search(
        r"\btop\s+(\d+)\b",
        normalized_question,
    )

    if top_match:
        requested_limit = int(
            top_match.group(1)
        )

        query.limit = max(
            1,
            min(requested_limit, 1000),
        )

        query.order = "desc"

    # Detect bottom queries.
    bottom_match = re.search(
        r"\bbottom\s+(\d+)\b",
        normalized_question,
    )

    if bottom_match:
        requested_limit = int(
            bottom_match.group(1)
        )

        query.limit = max(
            1,
            min(requested_limit, 1000),
        )

        query.order = "asc"

    if query.limit is None:
        query.limit = 100

    return query


def plan_query(
    question: str,
) -> SemanticQuery:
    """
    Convert a natural-language question into a
    validated SemanticQuery.
    """

    if not question.strip():
        raise ValueError(
            "Question cannot be empty."
        )

    planner = create_query_planner()

    messages = [
        {
            "role": "system",
            "content": build_system_prompt(),
        },
        {
            "role": "user",
            "content": question,
        },
    ]

    result = planner.invoke(messages)

    if result is None:
        raise ValueError(
            "The model did not return "
            "a semantic query."
        )

    result = apply_query_rules(
        question,
        result,
    )

    validate_semantic_query(result)

    return result


def main() -> None:
    """
    Run the complete MetricMind pipeline.
    """

    user_question = input(
        "Ask MetricMind: "
    )

    try:
        semantic_query = plan_query(
            user_question
        )

        cube_query = semantic_to_cube(
            semantic_query
        )

        sql, parameters = build_sql(
            semantic_query
        )

        print(
            "\nGenerated Semantic Query:\n"
        )

        print(
            json.dumps(
                semantic_query.model_dump(),
                indent=2,
            )
        )

        print(
            "\nConverted Cube Query:\n"
        )

        print(
            json.dumps(
                cube_query,
                indent=2,
            )
        )

        print(
            "\nGenerated SQL:\n"
        )

        print(sql)

        print(
            "\nSQL Parameters:\n"
        )

        print(parameters)

        results = execute_query(
            sql,
            parameters,
        )

        print(
            "\nSnowflake Results:\n"
        )

        print(
            json.dumps(
                results,
                indent=2,
                default=str,
            )
        )

    except Exception as error:
        print(
            f"\nError: {error}"
        )


if __name__ == "__main__":
    main()