
    
version: 2

models:
  - name: stg_global_superstore
    description: Cleaned staging model for the Global Superstore dataset

    columns:
      - name: row_id
        tests:
          - unique
          - not_null

      - name: order_id
        tests:
          - not_null

      - name: order_date
        tests:
          - not_null

      - name: sales
        tests:
          - not_null

      - name: category
        tests:
          - not_null
          - accepted_values:
              values:
                - Furniture
                - Office Supplies
                - Technology
